# Generated by Django 6.0.4 on 2026-05-03 01:33

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('horizon', models.CharField(choices=[('short', 'Curto prazo'), ('medium', 'Médio prazo'), ('long', 'Longo prazo')], max_length=20, verbose_name='horizonte')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='data alvo')),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('next', 'Próximo'), ('in_progress', 'Em andamento'), ('waiting', 'Aguardando'), ('done', 'Concluído')], default='next', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'Meta profissional',
                'verbose_name_plural': 'Metas profissionais',
                'ordering': ['target_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140, verbose_name='nome')),
                ('subject', models.CharField(blank=True, max_length=140, verbose_name='matéria')),
                ('instructor', models.CharField(blank=True, max_length=140, verbose_name='professor')),
                ('status', models.CharField(choices=[('planned', 'Planejada'), ('in_progress', 'Cursando'), ('done', 'Concluída')], default='planned', max_length=20, verbose_name='status')),
                ('current_grade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='nota atual')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=160, verbose_name='descrição')),
                ('entry_type', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa'), ('investment', 'Investimento')], max_length=20, verbose_name='tipo')),
                ('category', models.CharField(max_length=120, verbose_name='categoria')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='data')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'Movimento financeiro',
                'verbose_name_plural': 'Movimentos financeiros',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FitnessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, verbose_name='atividade')),
                ('workout_type', models.CharField(max_length=120, verbose_name='tipo de treino')),
                ('performed_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='data')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='duração (min)')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'Registro fitness',
                'verbose_name_plural': 'Registros fitness',
                'ordering': ['-performed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140, verbose_name='hábito')),
                ('category', models.CharField(max_length=120, verbose_name='categoria')),
                ('frequency', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], max_length=20, verbose_name='frequência')),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('next', 'Próximo'), ('in_progress', 'Em andamento'), ('waiting', 'Aguardando'), ('done', 'Concluído')], default='in_progress', max_length=20, verbose_name='status')),
                ('streak', models.PositiveIntegerField(default=0, verbose_name='sequência atual')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'Hábito',
                'verbose_name_plural': 'Hábitos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(max_length=160, verbose_name='tema')),
                ('category', models.CharField(max_length=120, verbose_name='categoria')),
                ('concept', models.TextField(verbose_name='conceito')),
                ('example', models.TextField(blank=True, verbose_name='exemplo')),
                ('code_reference', models.CharField(blank=True, max_length=255, verbose_name='referência de código')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'Base de conhecimento',
                'verbose_name_plural': 'Base de conhecimento',
                'ordering': ['category', 'topic'],
            },
        ),
        migrations.CreateModel(
            name='LessonLearned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('problem', models.TextField(verbose_name='problema')),
                ('solution', models.TextField(verbose_name='como resolveu')),
                ('learning', models.TextField(verbose_name='o que aprendeu')),
                ('impact', models.TextField(blank=True, verbose_name='impacto')),
            ],
            options={
                'verbose_name': 'Erro e lição',
                'verbose_name_plural': 'Erros e lições',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LifeGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('area', models.CharField(choices=[('body', 'Corpo'), ('money', 'Dinheiro'), ('career', 'Carreira'), ('spiritual', 'Espiritual')], max_length=20, verbose_name='área')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='data alvo')),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('next', 'Próximo'), ('in_progress', 'Em andamento'), ('waiting', 'Aguardando'), ('done', 'Concluído')], default='next', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'Meta de vida',
                'verbose_name_plural': 'Metas de vida',
                'ordering': ['target_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ReadingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('author', models.CharField(blank=True, max_length=140, verbose_name='autor')),
                ('category', models.CharField(blank=True, max_length=120, verbose_name='categoria')),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('next', 'Próximo'), ('in_progress', 'Em andamento'), ('waiting', 'Aguardando'), ('done', 'Concluído')], default='next', max_length=20, verbose_name='status')),
                ('insight', models.TextField(blank=True, verbose_name='insight principal')),
            ],
            options={
                'verbose_name': 'Leitura e reflexão',
                'verbose_name_plural': 'Leituras e reflexões',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RelationshipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('item_type', models.CharField(choices=[('contact', 'Contato'), ('event', 'Evento'), ('networking', 'Networking')], max_length=20, verbose_name='tipo')),
                ('next_action', models.CharField(blank=True, max_length=255, verbose_name='próxima ação')),
                ('reference_date', models.DateField(blank=True, null=True, verbose_name='data de referência')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'Relacionamento',
                'verbose_name_plural': 'Relacionamentos',
                'ordering': ['reference_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('stage', models.PositiveIntegerField(default=1, verbose_name='etapa')),
                ('resource_type', models.CharField(choices=[('course', 'Curso'), ('video', 'Vídeo'), ('article', 'Artigo'), ('project', 'Projeto'), ('book', 'Livro')], max_length=20, verbose_name='tipo')),
                ('resource', models.CharField(max_length=255, verbose_name='recurso')),
                ('source_url', models.URLField(blank=True, verbose_name='link')),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('next', 'Próximo'), ('in_progress', 'Em andamento'), ('waiting', 'Aguardando'), ('done', 'Concluído')], default='next', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('sort_order', models.PositiveIntegerField(default=1, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'Passo do roadmap',
                'verbose_name_plural': 'Passos do roadmap',
                'ordering': ['stage', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SemesterPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('semester', models.CharField(max_length=60, verbose_name='semestre')),
                ('goal', models.TextField(verbose_name='objetivo')),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('next', 'Próximo'), ('in_progress', 'Em andamento'), ('waiting', 'Aguardando'), ('done', 'Concluído')], default='next', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'Planejamento de semestre',
                'verbose_name_plural': 'Planejamentos de semestre',
                'ordering': ['semester', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, verbose_name='tema')),
                ('stack', models.CharField(blank=True, max_length=120, verbose_name='stack')),
                ('concept', models.TextField(verbose_name='conceito')),
                ('example', models.TextField(blank=True, verbose_name='exemplo')),
                ('mistake', models.TextField(blank=True, verbose_name='erro importante')),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('next', 'Próximo'), ('in_progress', 'Em andamento'), ('waiting', 'Aguardando'), ('done', 'Concluído')], default='next', max_length=20, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Aprendizado técnico',
                'verbose_name_plural': 'Aprendizados técnicos',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WorkProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('technologies', models.CharField(blank=True, max_length=255, verbose_name='tecnologias')),
                ('role', models.CharField(blank=True, max_length=120, verbose_name='papel')),
                ('impact', models.TextField(blank=True, verbose_name='impacto')),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('next', 'Próximo'), ('in_progress', 'Em andamento'), ('waiting', 'Aguardando'), ('done', 'Concluído')], default='in_progress', max_length=20, verbose_name='status')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'Projeto de trabalho',
                'verbose_name_plural': 'Projetos de trabalho',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WorkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('task_type', models.CharField(blank=True, max_length=80, verbose_name='tipo')),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('next', 'Próximo'), ('in_progress', 'Em andamento'), ('waiting', 'Aguardando'), ('done', 'Concluído')], default='backlog', max_length=20, verbose_name='status')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='prioridade')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'Atividade de trabalho',
                'verbose_name_plural': 'Atividades de trabalho',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademicTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('next', 'Próximo'), ('in_progress', 'Em andamento'), ('waiting', 'Aguardando'), ('done', 'Concluído')], default='backlog', max_length=20, verbose_name='status')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='prioridade')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.discipline', verbose_name='disciplina')),
            ],
            options={
                'verbose_name': 'Tarefa acadêmica',
                'verbose_name_plural': 'Tarefas acadêmicas',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademicProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('next', 'Próximo'), ('in_progress', 'Em andamento'), ('waiting', 'Aguardando'), ('done', 'Concluído')], default='next', max_length=20, verbose_name='status')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.discipline', verbose_name='disciplina')),
            ],
            options={
                'verbose_name': 'Projeto acadêmico',
                'verbose_name_plural': 'Projetos acadêmicos',
                'ordering': ['due_date', 'title'],
            },
        ),
    ]
